export async function seed(knex) {
  await knex('menu_items').del();

  await knex('menu_items').insert([
    {
      id: 1,
      name: 'Margherita Pizza',
      description: 'Classic pizza with fresh mozzarella, tomato sauce, and basil',
      price: 1800,
      image: 'https://example.com/images/margherita.jpg',
      vendor_id: 1,
    },
    {
      id: 2,
      name: 'Pepperoni Pizza',
      description: 'Traditional pizza topped with pepperoni and mozzarella cheese',
      price: 2000,
      image: 'https://example.com/images/pepperoni.jpg',
      vendor_id: 1,
    },
    {
      id: 3,
      name: 'Hawaiian Pizza',
      description: 'Pizza with ham, pineapple, and mozzarella cheese',
      price: 2200,
      image: 'https://example.com/images/hawaiian.jpg',
      vendor_id: 1,
    },
    {
      id: 4,
      name: 'Supreme Pizza',
      description: 'Loaded with pepperoni, sausage, peppers, onions, and mushrooms',
      price: 2500,
      image: 'https://example.com/images/supreme.jpg',
      vendor_id: 1,
    },
    {
      id: 5,
      name: 'Classic Cheeseburger',
      description: 'Juicy beef patty with cheese, lettuce, tomato, and special sauce',
      price: 1200,
      image: 'https://example.com/images/cheeseburger.jpg',
      vendor_id: 2,
    },
    {
      id: 6,
      name: 'Bacon BBQ Burger',
      description: 'Beef patty with crispy bacon, cheddar cheese, and BBQ sauce',
      price: 1500,
      image: 'https://example.com/images/bacon-bbq.jpg',
      vendor_id: 2,
    },
    {
      id: 7,
      name: 'Veggie Burger',
      description: 'Plant-based patty with fresh vegetables and vegan mayo',
      price: 1100,
      image: 'https://example.com/images/veggie-burger.jpg',
      vendor_id: 2,
    },
    {
      id: 8,
      name: 'Double Deluxe Burger',
      description: 'Two beef patties, double cheese, lettuce, tomato, and pickles',
      price: 1800,
      image: 'https://example.com/images/double-deluxe.jpg',
      vendor_id: 2,
    },
    {
      id: 9,
      name: 'California Roll',
      description: 'Crab, avocado, and cucumber wrapped in nori and rice',
      price: 800,
      image: 'https://example.com/images/california-roll.jpg',
      vendor_id: 3,
    },
    {
      id: 10,
      name: 'Salmon Sashimi',
      description: 'Fresh raw salmon slices served with soy sauce and wasabi',
      price: 1500,
      image: 'https://example.com/images/salmon-sashimi.jpg',
      vendor_id: 3,
    },
    {
      id: 11,
      name: 'Dragon Roll',
      description: 'Eel and cucumber topped with avocado and eel sauce',
      price: 1800,
      image: 'https://example.com/images/dragon-roll.jpg',
      vendor_id: 3,
    },
    {
      id: 12,
      name: 'Spicy Tuna Roll',
      description: 'Tuna mixed with spicy mayo, cucumber, and sesame seeds',
      price: 1200,
      image: 'https://example.com/images/spicy-tuna.jpg',
      vendor_id: 3,
    },
    {
      id: 13,
      name: 'Classic Beef Tacos',
      description: 'Three soft shell tacos with seasoned beef, lettuce, and cheese',
      price: 1000,
      image: 'https://example.com/images/beef-tacos.jpg',
      vendor_id: 4,
    },
    {
      id: 14,
      name: 'Chicken Quesadilla',
      description: 'Grilled chicken, cheese, and peppers in a flour tortilla',
      price: 1200,
      image: 'https://example.com/images/chicken-quesadilla.jpg',
      vendor_id: 4,
    },
    {
      id: 15,
      name: 'Carnitas Burrito',
      description: 'Slow-cooked pork, rice, beans, cheese, and salsa in a large tortilla',
      price: 1400,
      image: 'https://example.com/images/carnitas-burrito.jpg',
      vendor_id: 4,
    },
    {
      id: 16,
      name: 'Fish Tacos',
      description: 'Grilled fish with cabbage slaw, lime, and chipotle sauce',
      price: 1300,
      image: 'https://example.com/images/fish-tacos.jpg',
      vendor_id: 4,
    },
    {
      id: 17,
      name: 'Spaghetti Carbonara',
      description: 'Creamy pasta with bacon, eggs, parmesan cheese, and black pepper',
      price: 1600,
      image: 'https://example.com/images/carbonara.jpg',
      vendor_id: 5,
    },
    {
      id: 18,
      name: 'Fettuccine Alfredo',
      description: 'Rich and creamy alfredo sauce with parmesan cheese over fettuccine',
      price: 1500,
      image: 'https://example.com/images/alfredo.jpg',
      vendor_id: 5,
    },
    {
      id: 19,
      name: 'Lasagna',
      description: 'Layered pasta with meat sauce, ricotta, and mozzarella cheese',
      price: 1800,
      image: 'https://example.com/images/lasagna.jpg',
      vendor_id: 5,
    },
    {
      id: 20,
      name: 'Penne Arrabbiata',
      description: 'Spicy tomato sauce with garlic, red peppers, and fresh basil',
      price: 1400,
      image: 'https://example.com/images/arrabbiata.jpg',
      vendor_id: 5,
    },
  ]);
}

